### PR TITLE
[BREAKING CHANGE] Dynamic MQTT Topics for CVE/HRU remotes

### PR DESCRIPTION
**Pull request by benjamin-dcs**

### CODE REVIEW

**Comment by benjamin-dcs** [comment]
Just a WIP of what we could do with the topic, completely untested.

Removes the need to define the MQTT topic in `definitions.yaml`. As it's a 'constant' for each device, I didn't liked it anyway :D

**Comment by benjamin-dcs** [comment]
In this discussion, I think we should also decide between `noncve` vs `hru` in the back-end

**Comment by benjamin-dcs** [comment]
Also, shouldn't the setup be like this?:

image

**Comment by benjamin-dcs** [comment]
Why not? I feel this is way closer to reality. Remotes don't make sense 'standalone'. With that, they can either be connected to a `cve` or a `noncve` which requires them to be in the same `basetopic`. In theory, there could be two cve/noncve units with different remotes connected to both of them. This change should 'dynamically' allow for this situation.

**Comment by jasperslits** [comment]
The problem with the visual is that HRU is mutually exclusive with CVE but in addition you can have only WPU and WPU without autotemp etc. 

The original design reflects that. The multiple CVE/non-CVE is possible in theory but I would not bother with it up until there's an actual use-case reported. 

Remotes dont make sense standalone but it's possible to start with CVE/non-CVE and connect remotes at a later stage as pairing is more work.

**Comment by benjamin-dcs** [comment]
I see for the autotemp, but shouldnt the WPU be in the list? If you have a WPU + CVE/NONCVE you can add a second entry for the integration right?

**Comment by jasperslits** [comment]
Ok. I see your point now. So if you have the full bingo card for Itho: WPU, HRU, remotes and autotemp you'd have 3 entries? 

Perhaps that's cleaner. I guess I need to pull your changes and see what it looks like.

**Comment by benjamin-dcs** [comment]
I'd say we have 3 choices for the unit:
- CVE
- NONCVE
- WPU

Depending on the setup and the connected remotes and autotemp you need to configure them with the correct unit.

Remotes and autotemp should always be configures paired with a unit right? So I think max 3 entries

**Comment by benjamin-dcs** [comment]
This PR is only about dynamically setting the mqtt basetopic for remotes and autotemp. No refactoring of cve/noncve/wpu options yet. Guess that fits in this branch as well

**Comment by jasperslits** [comment]
> I'd say we have 3 choices for the unit:
> 
> * CVE
> * NONCVE
> * WPU
> 
> Depending on the setup and the connected remotes and autotemp you need to configure them with the correct unit.
> 
> Remotes and autotemp should always be configures paired with a unit right? So I think max 3 entries

Autotemp has its own physical add-on connected to the master unit so also a different base topic. 

Remotes always shares the base topic with the non-cve or cve unit.

**Comment by benjamin-dcs** [comment]
I see. Then I do believe we end up with config like my screenshot. I'd say 1 entry per physical unit

**Comment by benjamin-dcs** [comment]
@jasperslits This PR is pretty much final for me. So no refactoring of the Itho units. Do you agree with this change now?

As this PR is breaking, and I expect the refractor to be breaking as well we might want to combine those, at least in 1 release

**Comment by jasperslits** [comment]
Lgtm

**Pull request merged**
